### ISSUE TITLE
Roadmap MVP

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#1]
Tasks for the Landscaper MVP:

**Controller**:
- [x] Landscape Config Design
- [x] Implement OCI Registry/Local Location for definitions
  - [x] Local Registry
  - [x] OCI Registry
  - [x] Blob additional artifact handling
- [x] Installation Handling
  - [x] Create installations for referenced definitions
  - [x] Deletion Workflow
  - [x] Import Export Scheduling
  - [x] Construct Import Config
  - [x] Write Export Config
  - [x] OpenAPIV3 Validate Im- and Exports
  - [x] Implement Execution templating and Execution CR interaction
- [x] Implement Execution CRD Handler
- [x] Design and Implement Deploy Items
  - [x] Design and Implement Deploy Item Types
  - [x] Implement DeployItem communication in landscaper
 - [x] Implement Mock or NoOp Deployer
- [x] Improve Generation handling with subtree traversing
  - [x] Fetch Import Configuration from imports
  - [x] Validate imports with openapiv3 spec
  - [x] Generation handling
- [x] Implement Helm Deployer
  - [x] Implement Experimental Helm OCI Registry
  - [x] Use simple helm template and kubectl apply to apply helm charts
- [x] Make landscape config a simple installation
  - [x] only exports no imports
  - [x] maybe static exports
- [x] Implement Container Deployer
  - [x] own controller to handle DeployItems of type `container`
  - [x] implement initcontainer/secret mount for import config
  - [x] implement sidecar to watch the main container and update status/exports
- [x] Use Component Descriptor
  - [x] Add ComponentDefinitions as Artifacts to component descriptor (ref issue fro dev version deployments https://github.com/gardener/landscaper/issues/2)
- [x] test case with a subset of landscape setup components
  - nginx controller, dns-controller
  - virtual cluster 
- [x] Use proper Configuration file for landscaper controller
- [x] Own Dataobject for every exported and imported key
- [x] Validating/Mutating/Defaulting Webhooks
- [ ] Implement Skip
- [ ] Implement Abort
- [x] Deploy Targets
- [x] Content blob handling in deployers not only in the executors
- [x] DeployerInstallations
- [x] DAG in executions
  - [x] DAG Deletion
- [x] Helm Deployer Productization
  - [x] Remove deployed resources delta
  - [x] Support targets
- [x] Manifest Deployer
- [x] MultiCluster Container Support
- [x] Test Suite 
  - [x] Test for simple installation
  - [x] Test for simple example with data flow and scheduling
  - [x] Test for aggregated example
  - [x] Deployer Tests
- [ ] Documentation
  - [ ] Cleanup current outdated state
  - [ ] Instruction: How to build a blueprint/component
  - [ ] Operator guide: Hands-On Deploy landscaper and install first component
  - [ ] Concept overview
- [x] Deployer controller library
- [ ] Gardener Helper Functions/blueprints
  - [ ] Conversion ComponentDescriptor -> gardener image vector
  - [x] resolve/fetch tarred component from oci registry/blob store
- [x] State handling for deployer
- [ ] direct export from deploy executor/export executor has access to imports 

**Operations**
- [ ] Propagate failure to parent
- [ ] Logging stack (From Gardener Logging colleagues)
  - Nice to have
  - Too much effort
- [ ] Landscaper CLI
  - [ ] Show current executing installation
  - [ ] Show dependency tree
  - [ ] Retry specific component
  - [x] Add component descriptor push command

**CI/CD**:
- [ ] Add helm chart release step to cc-utils
- [x] Extend Component Descriptor to use helm charts + additional artifacts
- [x] Create Release Artifacts: Component Definitions
- [x] Docker image pipeline
- [x] Helm charts for landscaper + deployer and pipeline
- [x] ComponentDescriptor with helm charts for landscape repo

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
