### ISSUE TITLE
☂️ Issue for v1beta version

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#238]
Umbrella issue to track all the things we need to do and want to change when we create the new v1beta release.

Tasks:
- [ ] create new `v1beta1` crd version in [apis/core/v1beta1](apis/core/v1beta1)
- [ ] add beta version to crd and make it the default storage
- [ ] create conversion webhook to convert v1alpha1 to v1beta1: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#webhook-conversion
- [ ] update code to use new v1beta1 structs

Want to change:
- [ ] remove `subinstallations` attribute in Blueprint and replace it with  a `subinstallationExecutor` of type `plain`
  - [ ] add execution type plain and default to it
- [ ] rename `subinstallations` to `installations` to avoid confusion of `sub`-installations
- [ ] optimize boolean flags and make them more human readable: https://github.com/gardener/landscaper/issues/211
- [ ] remove repository context and registry pull secret, rather add a `DefaultContext` configuration
- [ ] remove installation scoped registry pull secrets and repository context and only allow a `ContextRef`
- [ ] adapt structure of `importDataMappings` to be similar to `deployExecutions`/`exportExecutions` (including `type` for templating engine)
- [ ] remove support for target reference by name and namespace in deployitem template in blueprint (see #414)
- [ ] remove support for `#` prefix in installation imports (see #414)
- [ ] enforce usage of `type` field for import declarations (remove defaulting depending on set fields)

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
