### ISSUE TITLE
New Type system

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#4]
/kind epic
/priority critical

Currently the landscapers type system is defined by `DataType` CR that are either defined by the landscaper, the operator or custom types from blueprints.
These `DataTypes` contains a OpenAPIV3Spec description of json or yaml data.

Disadvantages:
- cluster wide/ global type definitions
- no real sharing between components
- non-transparent versions/migrations and source of types.
- global naming which has to be followed by all blueprints

Advantage:
- Clear type system with static analysis of imported and exported types

As our current approach has the described issues the following approach was discussed.

#### Types 
The types are now described by json scheme not OpenAPIV3 as we anyways only used the schema definitions.
The jsonscheme definitions are defined inline in the blueprint as follows.
```yaml
apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

jsonSchemaVersion: "https://json-schema.org/draft/2019-09/schema" # defines the default jsonscheme version for all scheme in the docu

imports:
- name: A # imported key
  schema:
    "$schema": "https://json-schema.org/draft/2019-09/schema" # overwrite the default jsonschema version
    type: string
```

Reusability is necessary to not duplicate complex types as well as an easy way to describe big schemas.
Therefore it is possible to reference/define schemas with the following possibilities:
- Local blueprint schemas.
  Schemas can be defined in a blueprint (`.localTypes`) and referenced via the jsonscheme `$ref` with a special uri `local://<type name>`.
```yaml
localTypes:
    aws-credential: # inline
      type: number
imports:
- name: A 
  schema:
    $ref: "local://aws-credentials"
```
- Separate files in the blueprints filesystem.
  Schemas can be defined separate files in the blueprints filesystem and referenced via the jsonscheme `$ref` with a special uri `blueprint://<my>/<blueprint>/<path>`. This uri describes that the schema is read from `<blueprint-root>/<my>/<blueprint>/<path>`. The file has to contain a valid jsonscheme.
```yaml
imports:
- name: B
  schema:
    $ref: "blueprint://types/gcp-credentials" # read file from blueprint content
```
-  Component Descriptor.
  Schemas are defined externally by other components and are resources in the component's component descriptor. These components can then be defined as dependencies (`ComponentReference`) and the schema resources can be referenced via a special uri `cd:///componentReferences/etcd/localResources/my-type`. 
This uri translates directly to the resources defined in the component descriptor.

Note: we still need to discuss the depth of these references. Currently we only support resources of direct dependencies.
```yaml
imports:
- name: A
  schema:
    $ref: "cd:///componentReferences/etcd/localResources/my-type" # path in component descriptor
```

#### Export
Exports will also be defined with jsonschemas the same way as described above.
In addition, a version is introduced to the definition that will make it possible to export the same key(name) with different versions.
The version is optional and will be defaulted to `v1`.
A export is now uniquely identified by its name and version.
```yaml
exports:
- name: key1
  version: v1 # optional; defaults to "v1"
  schema:
    "$schema": "https://json-schema.org/draft/2019-09/schema" # optional, also defaulted to .jsonSchemaVersion
    type: string
```

The version change also leads to a change in the dataobjects as well as the import handling in Installations.
The Blueprint imports will not be changed as the validation is done via jsonschema not via a specific type anymore.<br>
The availability of exports in a version of a blueprint does now depend on the environment (blueprint version), thus the environment/context specific installations have to specify the version as part of its import mapping. The new Installation handling will be part of another backlog item (see #5 ).

`DataObjects` does now contain the data of a exported key with all exported versions.
> Note. we still do not store the schema for a version in the dataobject. This can cause the schema of a version to update which fine if only fields are added in a backwards compatible way. 
> The drawback is that the schema could also be changed incompatible but currently we we cannot check if a schema is changed compatible or incompatible. 
> Such a check could be added in the future (by comparing the old and the new jsonschema type) for better validation.
```yaml
 apiVersion: landscaper.gardener.cloud/v1alpha1
kind: DataObject
data:
  v1: <here comes the data>
```

**Tasks**:
- [x] use jsonscheme instead of openapiv3
  - [x] validate appropriate libraries to use (they must support custom resolvers for `$ref` attributes)
    - https://github.com/qri-io/jsonschema : lightwight, fast and easy to use library but currently no resolver support
    - https://github.com/xeipuuv/gojsonschema : not evaluated but support for resolvers
  - [x] implement custom uri resolvers for `blueprint`, `local` and `cd`
- [x] remove old `DataTypes` and their handling
- [x] update the import and export definitions in the Blueprints
- [x] update Export handling in Installations
  - [ ] Update data objects to store versions
