### ISSUE TITLE
☂️ Monitoring

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#48]
**How to categorize this issue?**

/area monitoring
/kind epic
/priority 3

Umbrella issue to expose landscaper and deployer metrics and tracing got the various reconcile loops.

*General*:
- [x] Expose controller runtime metrics (https://book-v1.book.kubebuilder.io/beyond_basics/controller_metrics.html)

*Landscaper*:
- [x] blueprint/component-descriptor artifact cache
- [ ] installations controller
  - [ ] add tracing through the reconcile flow
- [ ] executions controller
  - [ ]  add tracing through the reconcile flow

The issue is open for other aspects we can monitor

**Comment by hendrikKahl** [comment]
Additionally, I feel we should expose basic controller metrics for all deployers as well.

In terms of further metrics: Maybe it would be interesting, if deployers would expose the connection time metrics? 
Like, how long does it takes to fetch deploy items from a landscaper cluster as a histogram?

**Comment by schrodit** [comment]
> Additionally, I feel we should expose basic controller metrics for all deployers as well.
> 
> In terms of further metrics: Maybe it would be interesting, if deployers would expose the connection time metrics?
> Like, how long does it takes to fetch deploy items from a landscaper cluster as a histogram?

you mean how long does it take for a deploy item to be processed?
maybe thats something we can also include the deployer library. some of such kind of default metrics

**Comment by hendrikKahl** [comment]
> you mean how long does it take for a deploy item to be processed?
That would be another valid option. What I had in mind was focusing more on traffic when there is a distributed setup with deployers and landscaper running in separate clusters.

**Comment by hendrikKahl** [comment]
metrics added to OCI cache - https://github.com/gardener/component-cli/pull/3

**Comment by hendrikKahl** [comment]
a first implementation has been merged with #110 . This enables the landscaper-controller collect metrics of the controller-runtime and its OCI cache(s).

Meaningful next steps would include:
- [ ]  enable deployer-controllers to expose the same set of metrics
- [ ] write a meaningful prometheus scrape config and drop metrics which are not needed
- [ ] build a grafana dashboard to visualize the status of each controller

Additionally, it could be interesting to expand the cache metrics with a histogram that gives insight into the file sizes.

**Comment by schrodit** [comment]
We should also switch to [OpenTelementry](https://opentelemetry.io/docs/concepts/what-is-opentelemetry/) as poen standard for metrics.
In addition open telemetry supports traces which could be a good way to monitor our reconcile loops.

Also the controller-runtime is migrating towards that approach: https://github.com/kubernetes-sigs/controller-runtime/issues/305

**Comment by achimweigel** [comment]
@In-Ko closed because outdated and/or copied into internal project
