### ISSUE TITLE
Improved Imports in Installations

### ISSUE THREAD

**Issue by schrodit** [gardener/landscaper#5]
/kind epic
/priority critical

The type system of the landscaper will be changed as part of #4 .
Data is now validated via jsonschema and export can be versioned.

These changes need to be reflected in the imports of Installations.

In addition, the import mapping is enhanced by a templating system that could also transform data to more flexible when different independent blueprint a put together.

#### Imports
Currently the mapping and dataobject (export key) reference is done in one data structure in installations by just rewriting the key with `from: externalKey` and `to: internalKey`.

This mapping will be split into a explicit `import` and a `importMapping` section.<br>
The `import` section defines the requested data objects and their version that must be available in the system.<br>
The `importMapping` section defines the mapping of imported data objects to blueprint imports.
The mappings are generated by using the imports and the defined template.
 
Goals of this separation:
-  All required imported data objects are explicitly defined in the installation. 
> We could also think of defaulting these imports with the blueprint imports to avoid boilerplate.
- Separation between the current environment (semantic data) and the blueprint import

```yaml
apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation

imports:
  myKey:
    name: exportedDatatObjectA # read data from dataobject "exportedDatatObjectA"
    version: v1 # optional; will be defaulted to "v1"
  kubeconfig: 
    name: "virtual-garden-kubeconfig"
    version: v1

importMapping: # -> map[string]interface{} : input[import.name]
    A: (( imports.myKey ))
    B:
        A: (( imports.kubeconfig ))
        B: “some text”
   C: (( imports.C )) will be defaulted if not overwritten.
```

#### Exports
The export mapping apply the same separation as the imports.
The exported data objects are defined in `.spec.exports` and the corresponding mapping is defined in `.spec.exportMapping`.
The export mappings are evaluated when all subinstallations and deploy items are finished.

The difference to the import mapping is that the exported versions have to be considered during templating.

```yaml
apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation

exportMapping: # -> map[string]interface{} : input[import.name]
    A: (( imports.myKey.v1 ))
    B:
        A: (( imports.kubeconfig.v2 ))
        B: “some text”
   C: (( imports.C )) will be defaulted if not overwritten.

exports:
  A:
    name: exportedDatatObjectA # read data from dataobject "exportedDatatObjectA"
    version: v1 # optional; will be defaulted to "v1"
  B: 
    name: "virtual-garden-kubeconfig"
    version: v1
```

**Tasks**:
- [x] update installation definitions and structs
- [x] adjust import validation and construction
  - [x] integrate with templating language (only spiff?)
- [x] Implement defaulting for import mappings
  - [x] maybe also for imports
- [x] Update Documentation
- [x] Add unit/integration tests
